# Generated by Django 5.1.5 on 2025-02-10 12:19

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bigcategory',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(choices=[('Elektronika', 'Elektronika'), ('Maishiy texnika', 'Maishiy Texnika'), ('Mato', 'Mato'), ('Poyabzal', 'Poyabzal'), ('Aksesuar', 'Aksesuar'), ("Go'zallik va parvarish", 'Gozallik Va Parvarish'), ('Salomatlik', 'Salomatlik'), ("Uy ro'zg'or buyumlari", 'Uy Rozgor Buyumlari'), ('Qurilish va tamirlash', 'Qurilish Va Tamirlash'), ('Bolalar tavarlari', 'Bolalar Tovarlari'), ('Oziq ovqat', 'Oziq Ovqat'), ('Maishiy kimyoviy moddalar', 'Maishiy Kimyoviy Moddalar'), ('Sport va dam olish', 'Sport Va Dam Olish'), ('Kantselyariya', 'Kantselyariya'), ('Uy hayvonlari uchun mahsulotlar', 'Uy Hayvonlari Uchun'), ("Yozgi uy, Bog' va sabzavot bog'i", 'Yozgi Uy Bog Va Sabzavot Bogi')], max_length=255)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(null=True, upload_to='products/', verbose_name='Rasm')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brend')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name="O'lchami")),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Og'irligi")),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Materiali')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ishlab chiqarilgan mamlakat')),
                ('warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kafolat')),
                ('availability', models.BooleanField(default=True, verbose_name='Mavjudligi')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Reyting')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chegirma (%)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teglar')),
                ('extra_fields', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha xususiyatlar")),
                ('big_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_product', to='main.bigcategory')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('text', models.TextField(verbose_name='Fikr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(choices=[('Smartfonlar va telefonlar', 'Smartfonlar Va Telefonlar'), ('Kompyuter uskunalari', 'Kompyuter Uskunalari'), ('Soatlar va elektron budilniklar', 'Soatlar Va Elektron Budilniklar'), ('Kvadrokopterlar va aksessuarlar', 'Kvadrokopterlar Va Aksesuarlar'), ('Optik asboblar', 'Optik Asboblar'), ('Elektronika uchun aksessuarlar', 'Elektronika Uchun Aksesuarlar'), ('Navigatorlar', 'Navigatorlar'), ('Aqlli uy va xavfsizlik', 'Aqli Uy Va Xavfsizlik'), ('Naushniklar va audio uskunalar', 'Naushniklar Va Audio Uskunalar'), ('Aqlli soatlar va fitnes bilakuzuklar', 'Aqli Soatlar Va Fitnes Bilakuzuklar'), ('Noutbuklar, planshetlar va elektron kitoblar', 'Noutbuklar Planshetlar Va Elektron Kitoblar'), ('Foto va video uskunalar', 'Foto Va Video Uskunalar'), ('Televizorlar va video uskunalar', 'Televizorlar Va Video Uskunalar'), ('Geymetlar uchun mahsulotlar', 'Geymetlar Uchun Mahsulotlar'), ("Go'zallik uskunalari", 'Gozallik Uskunalari'), ('Iqlimni nazorat qilish uskunalari', 'Iqlimni Nazorat Qilish Uskunalari'), ('Maishiy texnika', 'Maishiy Texnika'), ('Katta maishiy texnika', 'Katta Maishiy Texnika'), ('Oshxona jihozlari', 'Oshxona Jihozlari'), ('Ayollar kiyimi', 'Ayollar Kiyimi'), ('Erkaklar kiyimi', 'Erkaklar Kiyimi'), ('Qizlar uchun kiyimlar', 'Qizlar Uchun Kiyimlar'), ("O'g'il bolalar uchun kiyimlar", 'Ogil Bolalar Uchun Kiyimlar'), ("Yangi tug'ilgan chaqaloqlar uchun kiyimlar", 'Yangi Tugilgan Chaqaloqlar Uchun Kiyimlar'), ('Ayollar poyabzali', 'Ayollar Poyabzali'), ('Erkaklar poyabzali', 'Erkaklar Poyabzali'), ('Qizlar uchun poyabzal', 'Qizlar Uchun Poyabzal'), ("O'g'il bolalar uchun poyabzal", 'Ogil Bolalar Uchun Poyabzal'), ('Poyafzal aksessuarlari', 'Poyafzal Aksesuarlari'), ('Ayollar uchun aksessuarlar', 'Ayollar Uchun Aksesuarlar'), ('Erkaklar uchun aksessuarlar', 'Erkaklar Uchun Aksesuarlar'), ('Qizlar uchun aksessuarlar', 'Qizlar Uchun Aksesuarlar'), ("O'g'il bolalar uchun aksessuarlar", 'Ogil Bolalar Uchun Aksesuarlar'), ('Sayohat aksessuarlari', 'Sayohat Aksesuarlari'), ("Chang'i aksessuarlari", 'Changi Aksesuarlari'), ('Diniy aksessuarlar', 'Diniy Aksesuarlar'), ('Grim surmoq, pardoz qilmoq; yasamoq, tuzmoq', 'Grim Surmoq Pardoz Qilmoq'), ('Yuzni parvarish qilish', 'Yuzni Parvarish Qilish'), ('Sochni parvarish qilish', 'Sochni Parvarish Qilish'), ('Tana parvarishi', 'Tana Parvarishi'), ('Manikyur va pedikyur', 'Manikyur Va Pedikyur'), ('Erkaklar uchun', 'Erkaklar Uchun'), ('Parfyumeriya', 'Parfyumeriya'), ('Tatuirovka saloni uchun uskunalar va materiallar', 'Tatuirovka Saloni Uchun Uskunalar Va Materiallar'), ('Dermakosmetika', 'Dermakosmetika'), ('Koreya kosmetikasi', 'Koreya Kosmetikasi'), ('Shaxsiy gigiena', 'Shaxsiy Gigiena'), ('Professional kosmetika', 'Professional Kosmetika'), ('Vitaminlar va xun takviyeleri', 'Vitaminlar Va Xun Takviyeleri'), ('Intim kosmetika', 'Intim Kosmetika'), ('Massaj va massaj uskunalari', 'Massaj Va Massaj Uskunalari'), ('Tibbiy mahsulotlar va sarf materiallari', 'Tibbiy Mahsulotlar Va Sarf Materiallari'), ('Tibbiy asboblar', 'Tibbiy Asboblar'), ('Optika', 'Optika'), ('Ortopedik mahsulotlar', 'Ortopedik Mahsulotlar'), ('Prezervativlar va moylash materiallari', 'Prezervativlar Va Moylash Materiallari'), ('Sport ovqatlanishi', 'Sport Ovqatlanishi'), ('Reabilitatsiya mahsulotlari', 'Reabilitatsiya Mahsulotlari'), ('Oshxona buyumlari', 'Oshxona Buyumlari'), ("To'qimachilik", 'Toqimachilik'), ("Uy-ro'zg'or buyumlari", 'Uy Rozgor Buyumlari'), ('Narsalarni saqlash', 'Narsalarni Saqlash'), ('Dekor va interyer', 'Dekor Va Interyer'), ("Uy o'simliklari mahsulotlari", 'Uy Osimliklari Mahsulotlari'), ('Hammom va sauna mahsulotlari', 'Hammom Va Sauna Mahsulotlari'), ('Bayram mahsulotlari', 'Bayram Mahsulotlari'), ('Mebel', 'Mebel'), ("Qo'l asboblari va jihozlari", 'Qol Asboblari Va Jihozlari'), ('Santexnika', 'Santexnika'), ('Qurilish uskunalari', 'Qurilish Uskunalari'), ('Elektr', 'Elektr'), ('Yoritish', 'Yoritish'), ('Ventilyatsiya', 'Ventilyatsiya'), ('Sarf materiallari va uskunalar', 'Sarf Materiallari Va Uskunalar'), ('Tugatish materiallari', 'Tugatish Materiallari'), ("Uy va bog' uchun suv ta'minoti", 'Uy Va Bog Uchun Suv Taminoti'), ('Asboblar', 'Asboblar'), ('Mahkamlagichlar va armatura', 'Mahkamlagichlar Va Armatura'), ('Isitish', 'Isitish'), ('Gigiena va tagliklar', 'Gigiena Va Tagliklar'), ('Bolalar xonasi', 'Bolalar Xonasi'), ('Bolalar sporti va faol dam olish', 'Bolalar Sporti Va Faol Dam Olish'), ('Bolalar ovqati', 'Bolalar Ovqati'), ('Bolalar ijodiyoti', 'Bolalar Ijodiyati'), ("O'yinchoqlar va o'yinlar", 'Oyinchoqlar Va Oyinlar'), ("Aravachalar va avtomobil o'rindiqlari", 'Aravachalar Va Avtomobil Orindiqlari'), ('Oziqlantirish mahsulotlari', 'Oziqlantirish Mahsulotlari'), ('Onalar uchun mahsulotlar', 'Onalar Uchun Mahsulotlar'), ('Faol dam olish', 'Faol Dam Olish'), ('Velosport', 'Velosport'), ('Sport', 'Sport'), ('Oziq ovqat', 'Oziq Ovqat'), ('Suv sporti va suvda dam olish', 'Suz Sporti Va Suvda Dam Olish'), ('Qishki sport turlari', 'Qishki Sport Turlari'), ('Ochiq havoda dam olish, baliq ovlash va ov qilish', 'Ochiq Havoda Dam Olish Baliq Ovlash Va Ov Qilish'), ('Rolikli konkilar, uskunalar va ehtiyot qismlar', 'Rolitli Konkilar Uskunalar Va Ehtiyot Qismlar'), ('Skuterlar va aksessuarlar', 'Skuterlar Va Aksessuarlar'), ('Erkin vaznlar', 'Erkin Vaznlar'), ('Skeytbording', 'Skeytbording'), ('Mashq qilish mashinalari', 'Mashq Qilish Mashinalari'), ('Fitnes va yoga', 'Fitnes Va Yoga'), ('Elektr transporti', 'Elektr Transporti'), ("Yog'lar, soslar va ziravorlar", 'Yog Lar Soslar Va Ziravorlar'), ('Choy, qahva va kakao', 'Choy Qahva Va Kakao'), ('Suv, sharbatlar, ichimliklar', 'Suv Sharbatlar Ichimliklar'), ('Pishirilgan mahsulotlar va shirinliklar', 'Pishirilgan Mahsulotlar Va Shirinliklar'), ('Asal, murabbo, shirin konservalar', 'Asal Murabbo Shirin Konserverlar'), ("Aperatifler, yong'oqlar va urug'lar", 'Aperatifler Yongoqlar Va Uruglar'), ("Sog'lom ovqatlanish", 'Soglom Ovqatlarnish'), ('Saqlash', 'Saklash'), ('Makaron, don va nonushta donlari', 'Makaron Don Va Nonushta Donlari'), ('Un, shakar va tuz', 'Un Shakar Va Tuz'), ('Pishiriqlar va shirinliklar uchun mahsulotlar', 'Pishiriklar Va Shirinliklar Uchun Mahsulotlar'), ('Hasharotlar va kemiruvchilarga qarshi vositalar', 'Hasharotlar Va Kemiruvchilarga Qarshi Vositalar'), ('Yuvish uchun vositalar', 'Yuvish Uchun Vositalar'), ('Tozalash va yuvish vositalari', 'Tozalash Va Yuvish Vositalari'), ('Poyabzallarni parvarish qilish uchun vositalar', 'Poyabzallarni Parvarish Qilish Uchun Vositalar'), ('Maishiy texnika parvarishi uchun vositalar', 'Maishiy Texnika Parvarishi Uchun Vositalar'), ('Idish yuvish mashinalari uchun vositalar', 'Idish Yuvish Mashinalari Uchun Vositalar'), ('Havoni musaffolashtirgichlar va neytralizatorlar', 'Havoni Musaffolashtirgichlar Va Neytralizatorlar'), ("Qog'oz mahsulotlari", 'Qog Oz Mahsulotlar'), ("Ko'rgazma taxtalari", 'Korgazma Tahtalari'), ('Kalkulyatorlar', 'Kalkulyatorlar'), ('Patronlar', 'Patronlar'), ('Stol stendlari va biznes karta egalari', 'Stol Stendlari Va Biznes Karta Egalari'), ('Savdo uchun uskunalar', 'Savdo Uchun Uskunalar'), ('Ofis jihozlari', 'Ofis Jihozlari'), ('Papkalar va fayllar', 'Papkalar Va Fayllar'), ('Muhr va shtamplar', 'Muhr Va Shtamplar'), ('Yozish asboblari', 'Yozish Asboblari'), ("Maktab va ta'lim mahsulotlari", 'Maktab Va Talim Mahsulotlari'), ('Chizma aksessuarlari', 'Chizma Aksessuarlari'), ('Veterinariya dorixonasi', 'Veterinariya Dorixonasi'), ('Gigiena', 'Gigiena'), ('Kemiruvchilar uchun', 'Kemiruvchilar Uchun'), ('Mushuklar uchun', 'Mushuklar Uchun'), ('Qushlar uchun', 'Qushlar Uchun'), ('Baliq va sudraluvchilar uchun', 'Baliq Va Sudraluvchilar Uchun'), ('Qishloq hayvonlari uchun', 'Qishloq Hayvonlari Uchun'), ('Itlar uchun', 'Itlar Uchun'), ("Bog 'uskunalari", 'Bog Uskunalari'), ('Hovuzlar va aksessuarlar', 'Hovuzlar Va Aksessuarlar'), ("Yozgi uy va bog'ni tartibga solish", 'Yozgi Uy Va Bog Ni Tartibga Solish'), ('Hayvonlar va hasharotlarga qarshi vositalar', 'Hayvonlar Va Hasharotlarga Qarshi Vositalar'), ('Piknik, barbekyu, panjara', 'Piknik Barbekyu Panjara'), ("Bog 'mebellari va bezaklari", 'Bog Mebellari Va Bezaklari'), ("Bog 'vosita", 'Bog Vosita'), ("Urug'lar va ko'chatlar", 'Uruglar Va Kochatlar'), ("O'g'itlar va o'simliklarni parvarish qilish", 'Ogitlar Va Osimliklarni Parvarish Qilish')], max_length=255)),
                ('big_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_category', to='main.bigcategory')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='small_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle_product', to='main.smallcategory'),
        ),
    ]
